### ISSUE TITLE
java.lang.IllegalStateException: Capability missing for uuid after death when clicking "Respawn" button with LuckPerms

### ISSUE THREAD

**Issue by asdfjkll2** [davo899/CobblemonTrainers#15]
Yesterday we encountered a bug on my Cobblemon server where when a non-OP player dies, and clicks respawn, it throws this error with a lot of other things, and it messes up their character where they have to relog. On my tests with Mohist, they can't log into the server at all (it times them out every time) until the server restarts. On forge, they are greeted with the "You died!" screen on login, and respawn with no items (keepInventory is on) and cannot interact with the world." Making the player OP seems to fix this issue but making every single player an OP would not be the best recommendation for a server since it's a public server. The issue also does not occur when either LuckPerms or CobblemonTrainers is not installed on the server. Attached are debug logs for both tests on Forge and Mohist server versions.
[forge server debug.log](https://github.com/davo899/CobblemonTrainers/files/14836577/forge.server.debug.log)
[mohist debug.txt](https://github.com/davo899/CobblemonTrainers/files/14836578/mohist.debug.txt)

**Comment by davo899** [comment]
Fixed in 0.9.11
