### ISSUE TITLE
Swap moves break the battle

### ISSUE THREAD

**Issue by ChosenMoren** [davo899/CobblemonTrainers#16]
I've tested some things related to this trainer and I found some game-breaking behavior. So, basically, if a trainer has a pokemon with U-Turn, Volt Switch or anything similar, the battle bugs out: after dealing with all the other trainer's pokemons, the original one that used u-turn never reapers and the battle ends prematurelly with an error message. 

To replicate the bug:
1 create a trainer
2 make some of his pokemon with u-turn
3 fail to OHKO that pokemon before he uses u-turn
.
The only excpetion case is the very first turn of the entire battle (not counting the first turn of a singular pokemon on the field), when it starts; this turn u-turn will not bug the entire battle, otherwise it will always break the thing; 

I've tested with u-turn and volt switch and 4 different pokemons, in 4 different slots too (1, 2, 3 and 4), but I think every 'swap after moving' move will break it.

**Comment by davo899** [comment]
i might be wrong, but this sounds a lot like the bug i fixed in 0.9.12 which i just released today. if you haven't updated to 0.9.12 maybe try it out again on that.

**Comment by ChosenMoren** [comment]
> i might be wrong, but this sounds a lot like the bug i fixed in 0.9.12 which i just released today. if you haven't updated to 0.9.12 maybe try it out again on that.

Yeah, that's it! Wow I didn't saw that the update launched today! Thanks a lot
