### ISSUE TITLE
Problem with Rechargeable Attacks

### ISSUE THREAD

**Issue by RaikouFan** [davo899/CobblemonTrainers#17]
Dear Developer,

I am using your mod rn and i gotta admit im impressed, the mod is really well made and its perfect for boss battles

Anyways there seems to be a problem with rechargable attacks like Hyperbeam or any other like roar if time from Dialga etc.
I hope you can fix it somehow and another thing, would it be possible to make Megamons compatible with Trainers?

**Comment by davo899** [comment]
Thanks! I just fixed this in 1.1.1. Are megamons not compatible?

**Comment by RaikouFan** [comment]
They do appear on the pokemon selecten but when i select them they just load as the regular version. Also thx for fixing and replying this fast, appreciate it
