### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by Nephalem0** [davo899/CobblemonTrainers#2]
Hi! I love the mod, but I was hoping to suggest if possible to make it that rather than trainers are all saved in 1 big json file, make groups be folders and have each trainer placed in a separate json file, it would make organizing for servers a lot easier!

**Comment by davo899** [comment]
This is a nice idea, I'll add it in the next update.

**Comment by davo899** [comment]
This is now out on 0.9.2
