### ISSUE TITLE
Request:

### ISSUE THREAD

**Issue by RaikouFan** [davo899/CobblemonTrainers#25]
Dear Developer,

For some reason Pokemon never use any priority moves in battles. This is unfortunate because a lot of pokemon are dependent on those moves. There is also a problem with status conditional attacks like Dream Eater where a pokemon will keep using the move even if it doesnt deal any damage(because the opposing pokemon isnt asleep). It would be great if the pokemon wouldn't always go for the highest damage attack and could setup to sweep a whole team. It would also make this already awesome mod more challenging and fun to play. Thank you for reading this and im hoping that there is a way to implement this request

**Comment by davo899** [comment]
Check out 1.1.10
