### ISSUE TITLE
Exp items unusable and crashes 

### ISSUE THREAD

**Issue by Jasseanwriting** [davo899/CobblemonTrainers#26]
I am unable to use  exp items and the game crashes unless it has the add-on installed. I tried to get rid of it, but the launcher keeps saying that "Error 1" has occurred. Also I am unable to battle any trainers as they keep saying that my trust is not high enough. If you need a crash report then please let me know

Thanks
Jas

**Comment by davo899** [comment]
Are you using radical cobblemon trainers?

**Comment by Jasseanwriting** [comment]
I am not, no
This is the only trainer mod I have

Many Thanks
Jasper Sean

Student Number: 19016298
________________________________

**Comment by davo899** [comment]
This mod does say "trust not high enough" in any situation at all, so I don't follow.

**Comment by davo899** [comment]
This mod doesn't say "trust not high enough" in any situation at all, so I don't follow.

Could you send the latest.log

**Comment by davo899** [comment]
I need to see the log to know what the problem is, please send it.
