### ISSUE TITLE
Please lower permission level

### ISSUE THREAD

**Issue by MarkusBordihn** [davo899/CobblemonTrainers#3]
The current commands are restricted to level 4 like:
```
        if (source.hasPermissionLevel(4)) return true;
```

Normally permission level 4 is only for server commands like server restart, server stop, ...

It should not be used for mod commands.

For this reason it should be lower to 2 or 3 which is the normal op level for such commands.

**Comment by davo899** [comment]
My mistake, will change it to 2.

**Comment by davo899** [comment]
This change is now out on 0.9.2
