### ISSUE TITLE
[Question] Are there plans to spawn the trainer's pokemon in the world during a battle?

### ISSUE THREAD

**Issue by CactusSquiggles** [davo899/CobblemonTrainers#6]
Basically what it says on the tin. I don't want to sound presumptuous or demanding because obviously this is a hobby-and-free-time project but I was curious if that was something on the docket. No worries either way, you've done a great job with this so far.

**Comment by davo899** [comment]
Thank you, and yeah I do plan to add this, I have a couple methods in mind on how to do it.
