### ISSUE TITLE
Trainers not using every Pokemon.

### ISSUE THREAD

**Issue by Cheesedoghotdog** [davo899/CobblemonTrainers#9]
I was fighting a trainer on my singleplayer world (yes, I'm lonely). It used baton pass a couple times and then, after only four of their six Pokemon were defeated, the battle was over with an error message.

**Comment by davo899** [comment]
Could you send the battle log?

This is likely a problem with Cobblemon's battle mechanics and isn't caused by the trainers, I've seen a few similar issues recently.

**Comment by Cheesedoghotdog** [comment]
[b78e3013-c944-43f0-9e3c-6806fe442a2d.txt](https://github.com/davo899/CobblemonTrainers/files/14473808/b78e3013-c944-43f0-9e3c-6806fe442a2d.txt)

**Comment by davo899** [comment]
Not sure exactly what went wrong here, from reading the log I see that you had fainted 5 pokemon (doduo > archen > farfetchd > taillow > pidgeotto). Cobblemon's battle AI should have switched to drifloon which had full HP, but for some reason thought it couldn't be switched in, so it caused an error. There's not really anything I can do here, should make a bug report in the Cobblemon discord with the battle log.
